name: Basic Table Tennis Pong Game

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{matrix.os}}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Linux
      run: |
        export SDL_VIDEODRIVER = dummy
      if: matrix.os == 'ubuntu-latest'
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pygame
    - name: Test with python
      run: |
        python main.py
